In [29]:
import numpy as np
x = np.array([1,2,3,4,5,6])
print(x)

[1 2 3 4 5 6]


In [30]:
# how to produce [[1,2,3], [4,5,6]] from x?
y = x.reshape((2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [31]:
# how to produce [[1, 3, 5], [2, 4, 6]] from x?
y = x.reshape((2,3), order='F')
print(y)

[[1 3 5]
 [2 4 6]]


In [32]:
A = np.array([[1, 3, 5], [2, 4, 6]])
print(A)

[[1 3 5]
 [2 4 6]]


In [33]:
# how to sum each column of A?
# i.e. produce [1+2, 3+4, 5+6]
print(np.sum(A, axis=0))

[ 3  7 11]


In [34]:
# how to sum each row of A?
# i.e. produce [1+3+5, 2+4+6]
print(np.sum(A, axis=1))

[ 9 12]


In [35]:
# how to get the index of the largest element in each column of A?
# i.e. produce [1, 1, 1]
print(np.argmax(A, axis=0))

[1 1 1]


In [26]:
# how to get the index of the largest element in each row of A?
# i.e. produce [2, 2]
print(np.argmax(A, axis=1))

[2 2]


In [27]:
# how to obtain a Boolean matrix B from A such that
# B[i,j] = True if A[i,j] > 2
# B[i,j] = False if A[i,j] <= 2
B = A > 2
print(B)

[[False  True  True]
 [False  True  True]]


In [28]:
# how to obtain all elements in A that are greater than 2?
# i.e. produce [3, 4, 5, 6]
B = A[A > 2]
print(B)

[3 5 4 6]
